version: "3.9"

services:
  app:
    build: ./app
    volumes:
      - ./input:/input
      - ./output:/output
      - ./temp:/temp
    environment:
      - MODEL_SIZE=base
    command: python main.py